### ISSUE TITLE
Adding a download data option to the settings page.

### ISSUE THREAD

**Issue by itsmais** [time-it-app/time-it-app#1]
In the settings page component, there should be a new option for downloading the data either in a `.pdf` or a `.csv` format. Currently, we only have a `copy to clipboard` option, where the data gets a little cleaner, before getting copied from `localStorage`.

**Comment by shub78910** [comment]
Hey, I think I can pick this up, let me know

**Comment by itsmais** [comment]
hello @shub78910 ! assigned to you :) good luck!

**Comment by shub78910** [comment]
Additional checks I added are:
1. while adding the fees: made that a type of number and gave it a min of "1"
2. Used placeholder instead of default as it has better user experience.
3. Gives an alert if the user leaves any field empty while adding the task.

Hope these are good enough and will enhance the project.
